- app/controllers/books_controller.rb
- config/routes.rb
- test/controllers/books_controller_test.rb
Just added a book controller and book routes
> add book controller and book routes

- Gemfile
- Gemfile.lock
- db/seeds.rb
added a seed file to create some fake data
> creates seed file to generate fake users & fake books

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
Please merge this stuff, thanks!
> Temporary updates for pages controller and home page view

- app/views/books/_author_info.html.erb
- app/views/users/show.html.erb
- db/migrate/20191118155537_add_profile_pic_to_user.rb
Added a link from a book to its user + a default user picture
> Connection book user

- db/seeds.rb
Just added a fake book description in the seed file.
> added fake book descriptions

- app/models/rental.rb
- app/models/review.rb
- app/models/user.rb
- app/views/users/_review.html.erb
- app/views/users/show.html.erb
- db/migrate/20191119122237_create_reviews.rb
- db/migrate/20191119135754_add_reader_to_review.rb
- db/seeds.rb
Added the review model, had to change the user model therefor and also added the reviews on the profile page
> Add review model

- app/controllers/books_controller.rb
- app/controllers/users_controller.rb
resolved the fact that you could only view the book or user page when logged in.
> skips authentication of user for show & search views

- app/controllers/books_controller.rb
- app/policies/book_policy.rb
now everyone can access the search
> adds authorization policy to books#search

- app/controllers/books_controller.rb
- app/views/books/show.html.erb
fixes bug that occurred when being not logged in and wanting to view book page
> checks if user logged in & displays form only then

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/users/_show.scss
- app/views/users/_review.html.erb
- app/views/users/show.html.erb
reviews are now on the profile again,
created links to books
default css is corrected
> fixed profile page and default css

- app/views/shared/_navbar.html.erb
adds book logo, current_user_profile_pic & links to add a book & current users profile
> customizes navbar

- db/seeds.rb
Just added real reviews and rentals to our seed file
> add real reviews and rentals to seed file

- app/views/books/show.html.erb
> add reviews to bookpage

- app/views/books/show.html.erb
- app/views/users/_review.html.erb
No bug if no reviews on profile page anymore
also added rating to reviews on profile page
> Fix review on profilepage if no reviews

- app/views/users/_review.html.erb
- db/seeds.rb
> fix the bug in seeds

- app/assets/stylesheets/pages/_home.scss
- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
> Fixed sticky bar, controller variable, opacity

- app/assets/stylesheets/pages/_home.scss
- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
Fixed sticky navbar, controller and spacing
> Fixed sticky navbar, controller and spacing

- app/controllers/reviews_controller.rb
- app/policies/review_policy.rb
- app/views/reviews/new.html.erb
- config/routes.rb
- db/schema.rb
- db/seeds.rb
Added a simple form for review + review controller + review routes + policy
They are not linked in our website by now (could not figure out how to do it LOL)
> Review form

- app/views/users/_review.html.erb
- app/views/users/show.html.erb
- db/schema.rb
- db/seeds.rb
HOPEFULLY this is the last time I have to fix this freakin review section on the profile page. Now there don't have to be two reviews for one rental ;)
> Final review fix profile

- config/routes.rb
I added a missing end in the routes file
> fixes routes by adding missing end

- app/assets/stylesheets/components/_avatar.scss
- app/controllers/books_controller.rb
authorises visitors to search + transforms avatars in circles
> authorises visitors to search + transforms avatars in circles

- app/controllers/books_controller.rb
- app/javascript/components/date.js.erb
- app/javascript/packs/application.js
datepicker without disabled dates... its just not working, sorry
> date picker refactored

- db/seeds.rb
> seed file update

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/users/_dashboard.scss
- app/controllers/rentals_controller.rb
- app/controllers/users_controller.rb
- app/views/rentals/_rentals_list.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_status.html.erb
- app/views/users/_dashboard_header.html.erb
- app/views/users/dashboard.html.erb
- app/views/users/list_books.html.erb
- app/views/users/list_hostings.html.erb
- app/views/users/list_readings.html.erb
I added styling to dashboard & created a css component for the card-design
More logic (grey out closed rentals, add button to create a review etc. ) is being implemented in a separate branch
> Improves UI for user dashboard

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_search_new.scss
- app/views/books/_search_bar.html.erb
- app/views/books/index.html.erb
- app/views/pages/home.html.erb
Added a search bar on result page
> add a search bar on result page

- app/views/pages/home.html.erb
> minor update in image sources

- app/controllers/books_controller.rb
> delete bug resolved
